services:
  - type: web
    name: nocodb
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: NC_AUTH_JWT_SECRET
        value: your-very-secret-key
      # Optional: Add your DB connection string if needed
      # - key: NC_DB
      #   value: mysql://user:pass@host/dbname
    disk:
      name: nocodb-data
      mountPath: /usr/app/data
      sizeGB: 1
